[package]
name = "PortaPad"
version = "0.1.0"
edition = "2024"
description = "ニッチで便利なインプット。"
license = "Proprietary"

[dependencies]
enigo        = "0.1"
futures-util = "0.3.31"
tokio         = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
tungstenite       = { version = "0.21", features = ["native-tls"] }

url = "2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webrtc = "0.9"
notify-rust = "4"
rdev = "0.5"
once_cell = "1.21.3"


[package.metadata.deb]
maintainer = "Povo43 <story-seller@outlook.com>"
priority = "optional"
copyright = "Copyright (c) 2025 Povo43"
section = "utils"
assets = [
    ["target/release/PortaPad", "usr/bin/", "755"],
    ["target/debian/portapad.service", "~/.config/systemd/user/", "644"],
]
maintainer-scripts = "target/debian/scripts"